# Full reference https://github.com/foundry-rs/foundry/tree/master/crates/config

[profile.default]
  auto_detect_solc = false
  block_timestamp = 1717200000 # June 1, 2024 at 00:00 GMT
  bytecode_hash = "none"
  evm_version = "shanghai"
  fuzz = { runs = 1_000 }
  gas_reports = ["SRF20"]
  optimizer = true
  optimizer_runs = 10_000
  out = "out"
  script = "script"
  solc = "0.8.26"
  src = "src"
  test = "test"

[profile.ci]
  fuzz = { runs = 10_000 }
  verbosity = 4

# Speed up compilation and tests during development
[profile.lite]
  optimizer = false

[doc]
  ignore = ["**/*.t.sol"]
  out = "docs"
  repository = "https://github.com/sablier-labs/stdlib"

[fmt]
  bracket_spacing = true
  int_types = "long"
  line_length = 120
  multiline_func_header = "all"
  number_underscore = "thousands"
  quote_style = "double"
  tab_width = 4
  wrap_comments = true

[rpc_endpoints]
  localhost = "http://localhost:8545"
  sepolia = "https://sepolia.infura.io/v3/${API_KEY_INFURA}"
